stages:
- deploy 

image: registry.gitlab.com/nebulrgroup/nebulr-build-containers:ui
before_script:
  - export GITLAB_NPM_REPOSITORY_TOKEN="${CI_JOB_TOKEN}"
  - ./init.sh

publish package:
  stage: deploy
  script:
    - npm run build
    - cd dist/nblocks-ionic && npm publish
  only:
    refs:
      - master